### ISSUE TITLE
TypeError: Path must be a string, Received undefined.

### ISSUE THREAD

**Issue by RupeshThakur11** [gladchinda/advanced-multer-node-sourcecode#1]
![issue](https://user-images.githubusercontent.com/10339410/38699143-d8346b32-3eb4-11e8-90b3-f1540474f691.PNG)

**Comment by gladchinda** [comment]
Hello @rkdaredevil 

This error indicates that the value of `process.env.AVATAR_STORAGE` is `undefined`, which means that the environment variables have not been loaded by `dotenv` into the `process.env` object.

Ensure that you followed the setup instructions [here](https://github.com/gladchinda/advanced-multer-node-sourcecode/blob/master/README.md).

Make sure you have the `dotenv` package installed.

```sh
npm install dotenv --save
```

Make sure you have  created a `.env` file on the root directory of the project that contains the following:

```ini
# Avatar Upload Variables

AVATAR_FIELD=avatar
AVATAR_BASE_URL=/uploads/avatars
AVATAR_STORAGE=public/uploads/avatars
```

**Comment by RupeshThakur11** [comment]
Hay Thanks,
Can I also collaborate with you on aws s3 and test cases for the same.

Regards
Rupesh Kumar

**Comment by gladchinda** [comment]
Yea sure you can. Quite engaged at the moment but can always make out time to collaborate.
